project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-On Exercise"
      menu:
        - text: "Hands-On Exercise 1"
          href: "Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true

editor: visual

